// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modul151.Todo.Api.DataAccess;

namespace Modul151.Todo.Api.Migrations
{
    [DbContext(typeof(TodoContext))]
    partial class TodoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Modul151.Todo.Api.Models.TodoItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Importance");

                    b.Property<bool>("IsComplete");

                    b.Property<string>("Message");

                    b.Property<string>("Name");

                    b.Property<long?>("UserID");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("Modul151.Todo.Api.Models.User", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<byte[]>("PwHash");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Modul151.Todo.Api.Models.TodoItem", b =>
                {
                    b.HasOne("Modul151.Todo.Api.Models.User", "User")
                        .WithMany("TodoItems")
                        .HasForeignKey("UserID");
                });
#pragma warning restore 612, 618
        }
    }
}
